### ISSUE TITLE
This pack doesn't work on server

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [Spiderach/VanillaReWoven#1]
I've tried to make a server with this modpack but it keeps crashing.
https://mclo.gs/DXrDlXW
Note: I've tried many times to launch the pack on a server and the log keeps telling me to remove mods, at this point I've removed like 10 mods.

**Comment by Spiderach** [comment]
That'd be because this pack was designed for client use, I hadn't posted a server-side equivalent yet. There are a TON of mods in this pack that only do anything on the client-side, and not all of them play nice when on the server side. This is a pretty common issue with modpacks, so with this pack or any other you'd like to host (that don't have a pre-made server pack) it's best to expect that you'll need to remove quite a few mods to get things running properly on the server.

**Comment by Spiderach** [comment]
Working on making a server pack if you still want it. There were a whopping 59 mods that only had a function for the client. Not all of those would've crashed the server, but some of them definitely do

**Comment by xXMolgadoGamer01Xx** [comment]
Yeah, that would be awesome :D

I'll look into it once it's realesed

**Comment by Spiderach** [comment]
There should now be a server zip available to go alongside the recent update. Sorry for the wait on that
